filetype indent plugin on
syntax on
set hidden
set wildmenu
set showcmd
set hlsearch
set ignorecase
set smartcase
set backspace=indent,eol,start
set autoindent
set breakindent
set ruler
set confirm
set number
set wrap
set linebreak
set cursorline
"language en_US
"language fr_FR
"set encoding=utf-8
"set encoding=latin1
"set fileencoding=utf-8
"set fileencodings=ucs-bom,utf-16,utf-8,latin-1
set errorbells
set novisualbell
